feat(chakra theme): Chakra theme sync with iFixit/ifixit
iFixit/react-components pull request #8
Opened 2021-10-07 00:16 UTC by ianrohde

The general purpose of this pull is to sync chakra themes to ease maintenance and increase compatibility.

1. Creates a single "source of truth" (core-primitives) for:

- breakpoints
- colors
- fonts

2. Switches `trueGray` to new values for `gray`, which are [now based on the Tailwind `coolGray` pallet](https://github.com/iFixit/core-primitives/commit/5a5a83525a8fc64c33be88a35e082cc778e50d41#diff-7aebb122a6ea8a2749d60cb05b7e103c9eae6e2e85e48d2d6cd9e20b63013975R210-R221). This was changed to make the transition more seamless when we switch existing colors.

2021-10-07 00:17 UTC, ianrohde commented
dev_block 🛑 on me getting the pull open that converts existing colors over the new values on iFixit/ifixit

2021-10-07 10:04 UTC, dhmacs reviewed
I'll check this against the collection page to see if I can spot other issues.

2021-10-08 14:50 UTC, bhuminson approved these changes
CR :dagger: but there may be issues as Massimo pointed out

2021-10-08 14:50 UTC, bhuminson commented on src/theme/foundations/breakpoints.ts
> +   xl: breakpoint.xl, // 1200px
Yes, I believe these are the breakpoints from core-primitives which is what we use on iFixit

2021-10-08 14:50 UTC, bhuminson commented on src/theme/foundations/breakpoints.ts
> +   xl: breakpoint.xl, // 1200px
Yes, I believe these are the breakpoints from core-primitives which is what we use on iFixit

2021-10-11 15:39 UTC, ianrohde commented on package.json
> +      "@core-ds/primitives": "^2.3.0"
@dhmacs apologies on the delay. What's the plan with migration? I haven't been involved in those conversations.

The Chakra theme is our source of truth, however previous to Chakra, it was core-primitives that were the source and they are used throughout our codebase. If we apply core-primitives _only_ at the Chakra theme level like this, there will be minimal maintenance but we still get the benefit of consistent styling and spacing.

2021-10-11 15:43 UTC, ianrohde commented on src/theme/foundations/breakpoints.ts
> +   xl: breakpoint.xl, // 1200px
Correct, this mirrors what we use on iFixit.

2021-10-12 05:36 UTC, dhmacs commented on package.json
> +      "@core-ds/primitives": "^2.3.0"
The plan was to inline primitives directly in Chakra theme, so we get rid of one more dependency. Otherwise changing some primitives would require to change core-primitives repo, and then updating this repo too, so it would be more maintenance burden

2021-10-12 15:21 UTC, ianrohde commented on package.json
> +      "@core-ds/primitives": "^2.3.0"
Not using the primitives has already created drift from our standardized breakpoints. We are setting ourselves up for further drift if we don't use them. This pull was a response to getting the footer component working on ifixit.com, but I guess I'm misunderstanding the purpose of the components in this repo.

2021-10-12 16:54 UTC, dhmacs commented on package.json
> +      "@core-ds/primitives": "^2.3.0"
Hey @ianrohde I think there's a misunderstanding here. I'm all in favor of using the primitives, I was just asking if we should just copy over the primitives in `@core-ds/primitives` here, instead of importing the dependency. 
Also, this does not need necessarily to happen know, but I would like to know if the plan is still to eventually merge the primitives into this package or if the plan is to maintain the primitives as a separate package.

2021-10-12 17:39 UTC, ianrohde commented on package.json
> +      "@core-ds/primitives": "^2.3.0"
Yeah @dhmacs you are right, there was a misunderstanding. I'm sorry about that.

Using `@core-ds/primitives` made the most sense since it's the same method for populating the Chakra theme values on iFixit. I maintain the primitives package, and I don't see a need for any breaking changes in the foreseeable future. `2.3.0` was created specifically to sync and eliminate context switching between core-primitives and Chakra's theming.

That said, I don't see my involvement often in building these components, so take it for what it's worth. If the dependency will be a nuisance, we can use static values from `@core-ds/primitives` instead, but that approach has its own potential issues.

2021-10-14 17:44 UTC, dhmacs requested changes
When testing this on `iFixit/react-commerce` repo I got this error:

<img width="989" alt="Screen Shot 2021-10-14 at 11 54 33" src="https://user-images.githubusercontent.com/4640135/137368872-97ba5ed8-b6a4-495f-a2dc-d423059771ce.png">

Basically `@core-ds/primitives` does not support named exports. To fix this it should be enough to change to a default import

```ts
import primitives from '@core-ds/primitives';
```

2021-10-19 17:52 UTC, ianrohde commented
Looking at updating primitives to ES6 to solve root issue.

2021-11-04 16:14 UTC, ianrohde commented
dev_block 🛑

2021-11-12 15:09 UTC, kwiens commented
What are the next steps on this?

2021-11-12 16:50 UTC, dhmacs commented
@kwiens 
> What are the next steps on this?

Convert all named imports as suggested by the review and this should be good to go

cc @ianrohde

2021-11-19 16:43 UTC, kwiens commented
@ianrohde What do you think your timeframe is on this?

2021-11-22 22:52 UTC, ianrohde commented
un_dev_block 🟢 

Been busy. This was always viewed as an optimization, not a necessity.

2021-11-24 00:13 UTC, ardelato commented
deploy_block ☁️  @ianrohde what changes should we expect to see?

I see that a footer menu item should now have a color of `gray-300` but it seems overwritten by global chakra styles?
![list item overwritten](https://user-images.githubusercontent.com/22064420/143147924-ff1c2809-96b5-41b6-a063-480cea466f78.png)

Aside from, it seems that `react-components` successfully builds and can be used in `react-commerce`, so QA 👍 

## Steps Taken:
1. Cloned this repo locally
2. Checked out this branch
3. Made sure to use `Node v14` and then ran `npm install`
4. I then ran the following
```shell
npm build
```
5. Then packed the compiled code with
```shell
npm pack
```
6. After packing it I cloned the `react-commerce` repo locally as well
7. I `cd`d into `react-commerce` and ran `npm install`
8. I then moved the `tgz` file created from step 5 into `react-commerce/frontend`
9. I then ran `npm install ifixit-react-components-0.3.1.tgz` 
10. I confirmed in the `frontend` package.json, then we were using the react-components from the `tgz` file
![tgz file used](https://user-images.githubusercontent.com/22064420/143148380-15262c35-c2e4-470f-83a7-3e126e77251a.png)
11. I then ran `npm run dev` from the project directory of `react-commerce`
12. I was able to successfully load the `backend` and `frontend` 
13. I the went to http://localhost:3000 and did not see any major issues

2021-11-24 18:29 UTC, ianrohde commented
@ardelato these are the same colors, they are just pulled from the primitives package now in `theme/foundations/colors.ts` instead of hard-coded. If primitives change for any reason in the future, those changes carry over to components in this repo.

2021-11-24 18:36 UTC, ardelato commented
>they are just pulled from the primitives package now in theme/foundations/colors.ts instead of hard-coded

Ahh gotcha! @ianrohde 

Then I am curious if this is also expected since I am not sure how the build is being created or packaged. It seems that the built type files do not include a reference to the primitive import?

![TS file vs Compiled Type File](https://user-images.githubusercontent.com/22064420/143295567-00f76470-3ac6-497b-b2cc-e35bf8dee88e.png)

2021-11-24 18:54 UTC, ianrohde commented
> Then I am curious if this is also expected since I am not sure how the build is being created or packaged. It seems that the built type files do not include a reference to the primitive import?

That sounds like a TypeScript compilation step. I wouldn't concern yourself with verification of any compiled code.

2021-11-24 22:21 UTC, ardelato commented
for sure, then un_deploy_block 👍

2021-11-26 10:44 UTC, dhmacs approved these changes
CR 🔥 

@ianrohde one small question: since `gray` token has been set with `coolGray` values, why not directly use `coolGray` token instead? With this change basically `coolGray` token is a duplicate of `gray`, or am I missing something?

2021-11-28 16:45 UTC, ianrohde commented
> @ianrohde one small question: since `gray` token has been set with `coolGray` values, why not directly use `coolGray` token instead? With this change basically `coolGray` token is a duplicate of `gray`, or am I missing something?

You got it @dhmacs. That was a decision based on usage in the iFixit code-base. Our old primitive color was `gray` and it seemed like an unnecessary context switch to force devs to remember to use anything else.

2021-12-04 00:02 UTC, josmfred approved these changes
CR :+1:

2021-12-06 17:16 UTC, ianrohde commented on src/theme/foundations/fonts.ts
> +import { fontFamily } from '@core-ds/primitives';
This is based on an outdated commit. The imports were changed from named to default in https://github.com/iFixit/react-components/pull/8/commits/2c20e0260c59496e3f24e53b6e810128b752504c

2021-12-06 17:20 UTC, ianrohde commented on src/theme/foundations/breakpoints.ts
> +   xl: breakpoint.xl, // 1200px
I added these so devs don't have to look up the values when working in this repo. Our primitive breakpoints haven't changed in 3 years.

2021-12-06 21:16 UTC, merged